python beginner_source/gastro/finetuning_multi6label.py -m "resnet18"
#python beginner_source/gastro/finetuning_multi6label.py -m "resnet34"
#python beginner_source/gastro/finetuning_multi6label.py -m "resnet50"
#python beginner_source/gastro/finetuning_multi6label.py -m "resnet101"
#python beginner_source/gastro/finetuning_multi6label.py -m "resnet152"
#python beginner_source/gastro/finetuning_multi6label.py -m "resnext50_32x4d"
#python beginner_source/gastro/finetuning_multi6label.py -m "resnext101_32x8d"

python beginner_source/gastro/finetuning_multi6label.py -m "vgg11"
#python beginner_source/gastro/finetuning_multi6label.py -m "vgg13"
#python beginner_source/gastro/finetuning_multi6label.py -m "vgg16"
#python beginner_source/gastro/finetuning_multi6label.py -m "vgg19"
#python beginner_source/gastro/finetuning_multi6label.py -m "vgg11_bn"
#python beginner_source/gastro/finetuning_multi6label.py -m "vgg13_bn"
#python beginner_source/gastro/finetuning_multi6label.py -m "vgg16_bn"
#python beginner_source/gastro/finetuning_multi6label.py -m "vgg19_bn"

python beginner_source/gastro/finetuning_multi6label.py -m "squeezenet1_0"
#python beginner_source/gastro/finetuning_multi6label.py -m "squeezenet1_1"

python beginner_source/gastro/finetuning_multi6label.py -m "densenet121"
#python beginner_source/gastro/finetuning_multi6label.py -m "densenet161"
#python beginner_source/gastro/finetuning_multi6label.py -m "densenet169"
#python beginner_source/gastro/finetuning_multi6label.py -m "densenet201"

python beginner_source/gastro/finetuning_multi6label.py -m "shufflenetv2_x0_5"
#python beginner_source/gastro/finetuning_multi6label.py -m "shufflenetv2_x1_0"
#python beginner_source/gastro/finetuning_multi6label.py -m "shufflenetv2_x1_5"
#python beginner_source/gastro/finetuning_multi6label.py -m "shufflenetv2_x2_0"

python beginner_source/gastro/finetuning_multi6label.py -m "inception3"