#python beginner_source/GI/finetuning_gi_4.py -m "squeezenet"
#python beginner_source/GI/finetuning_gi_4.py -m "resnet"
#python beginner_source/GI/finetuning_gi_4.py -m "alexnet"
#python beginner_source/GI/finetuning_gi_4.py -m "vgg"
#python beginner_source/GI/finetuning_gi_4.py -m "densenet"
#python beginner_source/GI/finetuning_gi_4.py -m "inception"

#python beginner_source/GI/finetuning_gi_4_aug1.py -m "squeezenet"
#python beginner_source/GI/finetuning_gi_4_aug1.py -m "resnet"
#python beginner_source/GI/finetuning_gi_4_aug1.py -m "alexnet"
#python beginner_source/GI/finetuning_gi_4_aug1.py -m "vgg"
#python beginner_source/GI/finetuning_gi_4_aug1.py -m "densenet"
#python beginner_source/GI/finetuning_gi_4_aug1.py -m "inception"

#python beginner_source/GI/finetuning_gi_4_aug2.py -m "squeezenet"
#python beginner_source/GI/finetuning_gi_4_aug2.py -m "resnet"
#python beginner_source/GI/finetuning_gi_4_aug2.py -m "alexnet"
#python beginner_source/GI/finetuning_gi_4_aug2.py -m "vgg"
#python beginner_source/GI/finetuning_gi_4_aug2.py -m "densenet"
#python beginner_source/GI/finetuning_gi_4_aug2.py -m "inception"
python beginner_source/GI/finetuning_gi_4_aug2.py -m "vgg11"
python beginner_source/GI/finetuning_gi_4_aug2.py -m "vgg13"
python beginner_source/GI/finetuning_gi_4_aug2.py -m "vgg16"
python beginner_source/GI/finetuning_gi_4_aug2.py -m "vgg19"

python beginner_source/GI/finetuning_gi_4_aug2.py -m "vgg13_bn"
python beginner_source/GI/finetuning_gi_4_aug2.py -m "vgg16_bn"
python beginner_source/GI/finetuning_gi_4_aug2.py -m "vgg19_bn"
