python beginner_source/GI/finetuning_gi_binary.py -m "squeezenet"
python beginner_source/GI/finetuning_gi_binary.py -m "resnet"
python beginner_source/GI/finetuning_gi_binary.py -m "alexnet"
python beginner_source/GI/finetuning_gi_binary.py -m "vgg"
python beginner_source/GI/finetuning_gi_binary.py -m "densenet"
python beginner_source/GI/finetuning_gi_binary.py -m "inception"

python beginner_source/GI/finetuning_gi_binary.py -m "squeezenet" -d "/data2/DB_GI/0/sample3"
python beginner_source/GI/finetuning_gi_binary.py -m "resnet" -d "/data2/DB_GI/0/sample3"
python beginner_source/GI/finetuning_gi_binary.py -m "alexnet" -d "/data2/DB_GI/0/sample3"
python beginner_source/GI/finetuning_gi_binary.py -m "vgg" -d "/data2/DB_GI/0/sample3"
python beginner_source/GI/finetuning_gi_binary.py -m "densenet" -d "/data2/DB_GI/0/sample3"
python beginner_source/GI/finetuning_gi_binary.py -m "inception" -d "/data2/DB_GI/0/sample3"