python beginner_source/GI/finetuning_gi_4_end.py -m "resnet18"
python beginner_source/GI/finetuning_gi_4_end.py -m "resnet34"
python beginner_source/GI/finetuning_gi_4_end.py -m "resnet50"
python beginner_source/GI/finetuning_gi_4_end.py -m "resnet101"
python beginner_source/GI/finetuning_gi_4_end.py -m "resnet152"
#python beginner_source/GI/finetuning_gi_4_end.py -m "resnext50_32x4d"
#python beginner_source/GI/finetuning_gi_4_end.py -m "resnext101_32x8d"

python beginner_source/GI/finetuning_gi_4_end.py -m "vgg11"
python beginner_source/GI/finetuning_gi_4_end.py -m "vgg13"
python beginner_source/GI/finetuning_gi_4_end.py -m "vgg16"
python beginner_source/GI/finetuning_gi_4_end.py -m "vgg19"
python beginner_source/GI/finetuning_gi_4_end.py -m "vgg11_bn"
python beginner_source/GI/finetuning_gi_4_end.py -m "vgg13_bn"
python beginner_source/GI/finetuning_gi_4_end.py -m "vgg16_bn"
python beginner_source/GI/finetuning_gi_4_end.py -m "vgg19_bn"

python beginner_source/GI/finetuning_gi_4_end.py -m "squeezenet1_0"
python beginner_source/GI/finetuning_gi_4_end.py -m "squeezenet1_1"

python beginner_source/GI/finetuning_gi_4_end.py -m "densenet121"
python beginner_source/GI/finetuning_gi_4_end.py -m "densenet161"
python beginner_source/GI/finetuning_gi_4_end.py -m "densenet169"
python beginner_source/GI/finetuning_gi_4_end.py -m "densenet201"

python beginner_source/GI/finetuning_gi_4_end.py -m "shufflenetv2_x0_5"
python beginner_source/GI/finetuning_gi_4_end.py -m "shufflenetv2_x1_0"
python beginner_source/GI/finetuning_gi_4_end.py -m "shufflenetv2_x1_5"
python beginner_source/GI/finetuning_gi_4_end.py -m "shufflenetv2_x2_0"

python beginner_source/GI/finetuning_gi_4_end.py -m "inception3"